# IBM watsonx.ai credentials
WATSONX_APIKEY = "k7mjsv-S8zwgXh3J8HSxXcq5dPi5ymx4sI_cOXNRwxHG"
WATSONX_URL    = "https://eu-de.ml.cloud.ibm.com"
PROJECT_ID     = "a7f886db-b9b4-43bc-a584-d4534a8d5ea5"

# IBM Cloud Object Storage credentials
COS_ENDPOINT       = "https://s3.us-south.cloud-object-storage.appdomain.cloud"
COS_API_KEY_ID     = "FkeoztxZPQ4jOMlVs-KvhKWCelTk4axk7rZxdnHq_u4G"
COS_INSTANCE_CRN   = "crn:v1:bluemix:public:cloud-object-storage:global:a/3c142e687cb244348e40436b815569f4:f3f1aecd-d2f2-4327-8e45-78f2752d8d48::"
COS_BUCKET_NAME    = "plagiarism-intelligence"
